// This file was generated by gir (https://github.com/gtk-rs/gir @ cea2f7c)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use glib::translate::*;
use glib::value::FromValue;
use glib::value::FromValueOptional;
use glib::value::SetValue;
use glib::value::Value;
use glib::StaticType;
use glib::Type;
use gobject_sys;
use polkit_agent_sys;

bitflags! {
    pub struct RegisterFlags: u32 {
        const NONE = 0;
        const RUN_IN_THREAD = 1;
    }
}

#[doc(hidden)]
impl ToGlib for RegisterFlags {
    type GlibType = polkit_agent_sys::PolkitAgentRegisterFlags;

    fn to_glib(&self) -> polkit_agent_sys::PolkitAgentRegisterFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<polkit_agent_sys::PolkitAgentRegisterFlags> for RegisterFlags {
    fn from_glib(value: polkit_agent_sys::PolkitAgentRegisterFlags) -> RegisterFlags {
        RegisterFlags::from_bits_truncate(value)
    }
}

impl StaticType for RegisterFlags {
    fn static_type() -> Type {
        unsafe { from_glib(polkit_agent_sys::polkit_agent_register_flags_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for RegisterFlags {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for RegisterFlags {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_flags(value.to_glib_none().0))
    }
}

impl SetValue for RegisterFlags {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_flags(value.to_glib_none_mut().0, this.to_glib())
    }
}

