// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from /usr/local/share/gir-1.0 (@ ???)
// DO NOT EDIT

use glib::translate::*;


//#[doc(alias = "polkit_agent_register_listener")]
//pub fn register_listener<P: IsA<polkit::Subject>>(listener: /*Ignored*/&Listener, subject: &P, object_path: &str) -> Result<(), glib::Error> {
//    unsafe { TODO: call ffi:polkit_agent_register_listener() }
//}
