// This file was generated by gir (https://github.com/gtk-rs/gir @ cea2f7c)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use glib::translate::*;
use polkit_agent_sys;


//pub fn register_listener<P: IsA<polkit::Subject>>(listener: /*Ignored*/&Listener, subject: &P, object_path: &str) -> Result<(), glib::Error> {
//    unsafe { TODO: call polkit_agent_sys:polkit_agent_register_listener() }
//}
