// This file was generated by gir (https://github.com/gtk-rs/gir @ cea2f7c)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

mod session;
pub use self::session::{Session, SessionClass};

mod flags;
pub use self::flags::RegisterFlags;

pub mod functions;

#[doc(hidden)]
pub mod traits {
}
