// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from /usr/local/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((guint) POLKIT_AUTHORITY_FEATURES_NONE);
    PRINT_CONSTANT((guint) POLKIT_AUTHORITY_FEATURES_TEMPORARY_AUTHORIZATION);
    PRINT_CONSTANT((guint) POLKIT_CHECK_AUTHORIZATION_FLAGS_ALLOW_USER_INTERACTION);
    PRINT_CONSTANT((guint) POLKIT_CHECK_AUTHORIZATION_FLAGS_NONE);
    PRINT_CONSTANT((gint) POLKIT_ERROR_CANCELLED);
    PRINT_CONSTANT((gint) POLKIT_ERROR_FAILED);
    PRINT_CONSTANT((gint) POLKIT_ERROR_NOT_AUTHORIZED);
    PRINT_CONSTANT((gint) POLKIT_ERROR_NOT_SUPPORTED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_ADMINISTRATOR_AUTHENTICATION_REQUIRED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_ADMINISTRATOR_AUTHENTICATION_REQUIRED_RETAINED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_AUTHENTICATION_REQUIRED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_AUTHENTICATION_REQUIRED_RETAINED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_AUTHORIZED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_NOT_AUTHORIZED);
    PRINT_CONSTANT((gint) POLKIT_IMPLICIT_AUTHORIZATION_UNKNOWN);
    return 0;
}
