// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from /usr/local/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PolkitAuthorityFeatures", sizeof(PolkitAuthorityFeatures), alignof(PolkitAuthorityFeatures));
    printf("%s;%zu;%zu\n", "PolkitCheckAuthorizationFlags", sizeof(PolkitCheckAuthorizationFlags), alignof(PolkitCheckAuthorizationFlags));
    printf("%s;%zu;%zu\n", "PolkitError", sizeof(PolkitError), alignof(PolkitError));
    printf("%s;%zu;%zu\n", "PolkitIdentityIface", sizeof(PolkitIdentityIface), alignof(PolkitIdentityIface));
    printf("%s;%zu;%zu\n", "PolkitImplicitAuthorization", sizeof(PolkitImplicitAuthorization), alignof(PolkitImplicitAuthorization));
    printf("%s;%zu;%zu\n", "PolkitSubjectIface", sizeof(PolkitSubjectIface), alignof(PolkitSubjectIface));
    return 0;
}
