// This file was generated by gir (https://github.com/gtk-rs/gir @ cea2f7c)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

mod action_description;
pub use self::action_description::{ActionDescription, ActionDescriptionClass};

mod authority;
pub use self::authority::{Authority, AuthorityClass};

mod authorization_result;
pub use self::authorization_result::{AuthorizationResult, AuthorizationResultClass};

mod details;
pub use self::details::{Details, DetailsClass};

mod identity;
pub use self::identity::{Identity, NONE_IDENTITY};
pub use self::identity::IdentityExt;

mod permission;
pub use self::permission::{Permission, PermissionClass};

mod subject;
pub use self::subject::{Subject, NONE_SUBJECT};
pub use self::subject::SubjectExt;

mod system_bus_name;
pub use self::system_bus_name::{SystemBusName, SystemBusNameClass};

mod temporary_authorization;
pub use self::temporary_authorization::{TemporaryAuthorization, TemporaryAuthorizationClass};

mod unix_group;
pub use self::unix_group::{UnixGroup, UnixGroupClass};

mod unix_netgroup;
pub use self::unix_netgroup::{UnixNetgroup, UnixNetgroupClass};

mod unix_process;
pub use self::unix_process::{UnixProcess, UnixProcessClass};

mod unix_session;
pub use self::unix_session::{UnixSession, UnixSessionClass};

mod unix_user;
pub use self::unix_user::{UnixUser, UnixUserClass};

mod enums;
pub use self::enums::Error;
pub use self::enums::ImplicitAuthorization;

mod flags;
pub use self::flags::AuthorityFeatures;
pub use self::flags::CheckAuthorizationFlags;

#[doc(hidden)]
pub mod traits {
    pub use super::IdentityExt;
    pub use super::SubjectExt;
}
