// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from /usr/local/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::Identity;
use glib::object::ObjectType as ObjectType_;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use std::ptr;

glib::wrapper! {
    /// An object representing a user identity on a UNIX system.
    ///
    /// # Implements
    ///
    /// [`trait@glib::ObjectExt`], [`IdentityExt`][trait@crate::prelude::IdentityExt]
    #[doc(alias = "PolkitUnixUser")]
    pub struct UnixUser(Object<ffi::PolkitUnixUser, ffi::PolkitUnixUserClass>) @implements Identity;

    match fn {
        type_ => || ffi::polkit_unix_user_get_type(),
    }
}

impl UnixUser {
    /// Get the user's name.
    ///
    /// # Returns
    ///
    /// User name string or [`None`] if user uid not found.
    #[doc(alias = "polkit_unix_user_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::polkit_unix_user_get_name(self.to_glib_none().0)) }
    }

    /// Gets the UNIX user id for `self`.
    ///
    /// # Returns
    ///
    /// A UNIX user id.
    #[doc(alias = "polkit_unix_user_get_uid")]
    #[doc(alias = "get_uid")]
    pub fn uid(&self) -> i32 {
        unsafe { ffi::polkit_unix_user_get_uid(self.to_glib_none().0) }
    }

    /// Sets `uid` for `self`.
    /// ## `uid`
    /// A UNIX user id.
    #[doc(alias = "polkit_unix_user_set_uid")]
    pub fn set_uid(&self, uid: i32) {
        unsafe {
            ffi::polkit_unix_user_set_uid(self.to_glib_none().0, uid);
        }
    }

    /// Creates a new [`UnixUser`][crate::UnixUser] object for `uid`.
    /// ## `uid`
    /// A UNIX user id.
    ///
    /// # Returns
    ///
    /// A [`UnixUser`][crate::UnixUser] object. Free with `g_object_unref()`.
    #[doc(alias = "polkit_unix_user_new")]
    pub fn new(uid: i32) -> Identity {
        unsafe { from_glib_full(ffi::polkit_unix_user_new(uid)) }
    }

    /// Creates a new [`UnixUser`][crate::UnixUser] object for a user with the user name
    /// `name`.
    /// ## `name`
    /// A UNIX user name.
    ///
    /// # Returns
    ///
    /// A [`UnixUser`][crate::UnixUser] object or [`None`] if `error` is set.
    #[doc(alias = "polkit_unix_user_new_for_name")]
    pub fn new_for_name(name: &str) -> Result<Option<Identity>, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::polkit_unix_user_new_for_name(name.to_glib_none().0, &mut error);
            if error.is_null() {
                Ok(from_glib_full(ret))
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    #[doc(alias = "uid")]
    pub fn connect_uid_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_uid_trampoline<F: Fn(&UnixUser) + 'static>(
            this: *mut ffi::PolkitUnixUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::uid\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_uid_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for UnixUser {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("UnixUser")
    }
}
