// This file was generated by gir (https://github.com/gtk-rs/gir @ cea2f7c)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use glib::object::ObjectType as ObjectType_;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::GString;
use glib_sys;
use polkit_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use Identity;

glib_wrapper! {
    pub struct UnixNetgroup(Object<polkit_sys::PolkitUnixNetgroup, polkit_sys::PolkitUnixNetgroupClass, UnixNetgroupClass>) @implements Identity;

    match fn {
        get_type => || polkit_sys::polkit_unix_netgroup_get_type(),
    }
}

impl UnixNetgroup {
    /// Gets the netgroup name for `self`.
    ///
    /// # Returns
    ///
    /// A netgroup name string.
    pub fn get_name(&self) -> GString {
        unsafe {
            from_glib_none(polkit_sys::polkit_unix_netgroup_get_name(self.to_glib_none().0))
        }
    }

    /// Sets `name` for `self`.
    /// ## `name`
    /// A netgroup name.
    pub fn set_name(&self, name: &str) {
        unsafe {
            polkit_sys::polkit_unix_netgroup_set_name(self.to_glib_none().0, name.to_glib_none().0);
        }
    }

    /// Creates a new `UnixNetgroup` object for `name`.
    /// ## `name`
    /// A netgroup name.
    ///
    /// # Returns
    ///
    /// A `UnixNetgroup` object. Free with `gobject::ObjectExt::unref`.
    pub fn new(name: &str) -> Identity {
        unsafe {
            from_glib_full(polkit_sys::polkit_unix_netgroup_new(name.to_glib_none().0))
        }
    }

    pub fn connect_property_name_notify<F: Fn(&UnixNetgroup) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<F: Fn(&UnixNetgroup) + 'static>(this: *mut polkit_sys::PolkitUnixNetgroup, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::name\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_name_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for UnixNetgroup {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "UnixNetgroup")
    }
}
