// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from /usr/local/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PolkitAgentListener", sizeof(PolkitAgentListener), alignof(PolkitAgentListener));
    printf("%s;%zu;%zu\n", "PolkitAgentListenerClass", sizeof(PolkitAgentListenerClass), alignof(PolkitAgentListenerClass));
    printf("%s;%zu;%zu\n", "PolkitAgentRegisterFlags", sizeof(PolkitAgentRegisterFlags), alignof(PolkitAgentRegisterFlags));
    return 0;
}
